"""
Morning deliverable: summarize training and showcase the results.

Run any time (during or after training):
    python finalize.py

Produces in out/:
  - model_alphabet.png : glyph sheet generated by the neural network (best.pt)
  - showcase_bank.png  : demo page from the real-ink bank (primary quality)
  - showcase_model.png : same text, neural fallback enabled
  - doc.pdf / doc_p*.png (via the LaTeX sample)
and prints training progress from the CSV log.
"""
import os
import csv
import numpy as np
from PIL import Image, ImageDraw

OUT = "out"
CKPT = "hw/checkpoints/best.pt"
LOG = "hw/checkpoints/train_log.csv"
os.makedirs(OUT, exist_ok=True)

DEMO = ("Esta pagina foi escrita por uma rede neural, na minha letra.\n"
        "The quick brown fox jumps over the lazy dog.\n"
        "Economia e mercados: juros, inflacao e valor presente.")


def training_status():
    if not os.path.exists(LOG):
        print("No training log yet.")
        return
    rows = list(csv.DictReader(open(LOG)))
    if not rows:
        return
    last = rows[-1]
    best = min(float(r["loss"]) for r in rows)
    print(f"Training: {len(rows)} epochs done | last loss {float(last['loss']):.2f} "
          f"| best loss {best:.2f} | beta {float(last['beta']):.2f} "
          f"| ~{float(last['sec']):.1f}s/epoch")


def alphabet_sheet():
    if not os.path.exists(CKPT):
        print("No checkpoint yet; skipping model sheet.")
        return
    from hw.model import GlyphGenerator
    g = GlyphGenerator(CKPT)
    chars = [c for c in "abcdefghijklmnopqrstuvwxyz"
             "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789" if c in g.cls_to_idx]
    cell, cols = 72, 13
    rows = (len(chars) + cols - 1) // cols
    sheet = Image.new("RGB", (cols * cell, rows * cell), (252, 250, 244))
    d = ImageDraw.Draw(sheet)
    npr = np.random.RandomState(0)
    for i, ch in enumerate(chars):
        r, c = divmod(i, cols)
        m = g.generate(ch, npr)
        gimg = Image.fromarray(((1 - m) * 255).astype(np.uint8)).convert("L")
        gimg = gimg.resize((cell - 16, cell - 16), Image.LANCZOS)
        sheet.paste(gimg, (c * cell + 8, r * cell + 8))
        d.rectangle([c*cell, r*cell, c*cell+cell-1, r*cell+cell-1], outline=(220, 220, 225))
    p = os.path.join(OUT, "model_alphabet.png")
    sheet.save(p)
    print("wrote", p)


def showcases():
    from hw.render import HandwritingRenderer
    HandwritingRenderer(seed=11).render(DEMO, xh=28, ruled=True).save(
        os.path.join(OUT, "showcase_bank.png"))
    print("wrote", os.path.join(OUT, "showcase_bank.png"))
    if os.path.exists(CKPT):
        from hw.model import GlyphGenerator
        r = HandwritingRenderer(seed=11, model=GlyphGenerator(CKPT))
        r.render(DEMO, xh=28, ruled=True).save(
            os.path.join(OUT, "showcase_model.png"))
        print("wrote", os.path.join(OUT, "showcase_model.png"))


if __name__ == "__main__":
    training_status()
    showcases()
    alphabet_sheet()
    # rebuild the LaTeX demo too
    os.system("python handwrite_latex.py out/sample.tex -o out/doc --ruled --seed 5")
    print("Done. See the out/ folder.")
